# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='Pub_name',
            field=models.CharField(max_length=32, verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.CharField(max_length=32, verbose_name='网站'),
        ),
    ]
